services:
  - type: web
    name: freecell-game-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: node backend/src/server.js
    envVars:
      - key: NODE_ENV
        value: production
    region: oregon
    branch: main
